name: Migrate docker image

on:
  workflow_dispatch:
    inputs:
      image:
        description: Image to migrate
        required: true
      tag:
        description: Tag to migrate
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Migrate image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
          dst: ghcr.io/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
