name: Continuous integration - JS lib

on:
  workflow_call:
    inputs:
      install-playwright:
        type: boolean
        required: false
        default: false
        description: 'Whether playwright dependencies should be installed before running tests. Defaults to false'

jobs:
  static-checks:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ['22.x']
        task: ['lint', 'types', 'build']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ${{ matrix.task }}

  unit-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ['20.x', '22.x', '23.x']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx playwright install chromium
        if: ${{ inputs.install-playwright }}
      - run: npm run test:ci
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage/clover.xml
