name: Continuous integration - PHP lib

on:
  workflow_call:
    inputs:
      extra-extensions:
        type: string
        required: false
        default: ''
        description: 'Extra PHP Extensions to install, besides the default ones'
      tests:
        type: boolean
        required: false
        default: true
        description: 'Enables execution of unit tests when value is true. Defaults to true'
      coverage-driver:
        type: string
        required: false
        description: '[Deprecated] This input is now ignored'

jobs:
  static-analysis:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.3']
        command: ['cs', 'stan']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: composer ${{ matrix.command }}

  unit-tests:
    if: ${{ inputs.tests }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.3', '8.4', '8.5']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: xdebug
      - run: composer install --no-interaction --prefer-dist
      - run: composer test:ci
      - uses: actions/cache/save@v4
        if: ${{ matrix.php-version == '8.3' }}
        with:
          path: build
          key: build-${{ matrix.php-version }}-${{ github.run_id }}

  upload-coverage:
    needs:
      - unit-tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - uses: actions/cache/restore@v4
        with:
          key: build-${{ matrix.php-version }}-${{ github.run_id }}
          path: build
      - name: Publish coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./build/clover.xml
