name: Continuous integration - PHP lib

on:
  workflow_call:
    inputs:
      extra-extensions:
        type: string
        required: false
        default: ''
        description: 'Extra PHP Extensions to install, besides the default ones'
      tests:
        type: boolean
        required: false
        default: true
        description: 'Enables execution of unit tests when value is true. Defaults to true'
      mutation-tests:
        type: boolean
        required: false
        default: true
        description: '[DEPRECATED] This is no longer used'
    secrets:
      INFECTION_BADGE_API_KEY:
        required: false
        description: '[DEPRECATED] This is no longer used'

jobs:
  static-analysis:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.3']
        command: ['cs', 'stan']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: composer ${{ matrix.command }}

  unit-tests:
    if: ${{ inputs.tests }}
    continue-on-error: ${{ matrix.php-version == '8.4' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: pcov
      - run: composer install --no-interaction --prefer-dist ${{ matrix.php-version == '8.4' && '--ignore-platform-req=php' || '' }}
      - run: composer test:ci
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.php-version == '8.3' }}
        with:
          name: build-${{ matrix.php-version }}
          path: build

  upload-coverage:
    needs:
      - unit-tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.php-version }}
          path: build
      - name: Publish coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./build/clover.xml

  delete-artifacts:
    needs:
      - upload-coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: build-*
