name: Continuous integration - PHP lib

on:
  workflow_call:
    inputs:
      extra-extensions:
        type: string
        required: false
        default: ''
        description: 'Extra PHP Extensions to install, besides the default ones'
      include-php-eight-two:
        type: boolean
        required: false
        default: false
    secrets:
      INFECTION_BADGE_API_KEY:
        required: false
        description: 'If provided, it will be used to publish the mutation score in Stryker dashboard'

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ${{ inputs.include-php-eight-two && fromJson('["8.2"]') || fromJson('["8.1"]') }}
        command: ['cs', 'stan']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: composer ${{ matrix.command }}

  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ${{ inputs.include-php-eight-two && fromJson('["8.1", "8.2"]') || fromJson('["8.1"]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: composer test:ci
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.php-version }}
          path: build

  mutation-tests:
    needs:
      - unit-tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ${{ inputs.include-php-eight-two && fromJson('["8.1", "8.2"]') || fromJson('["8.1"]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: ${{ inputs.extra-extensions }}
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.php-version }}
          path: build
      - run: composer infect:ci
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

  upload-coverage:
    needs:
      - unit-tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ${{ inputs.include-php-eight-two && fromJson('["8.2"]') || fromJson('["8.1"]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.php-version }}
          path: build
      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./build/clover.xml

  delete-artifacts:
    needs:
      - mutation-tests
      - upload-coverage
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ${{ inputs.include-php-eight-two && fromJson('["8.1", "8.2"]') || fromJson('["8.1"]') }}
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: build-${{ matrix.php-version }}
