name: Continuous integration - Web app

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
        description: 'NodeJS version to use'
      with-unit-tests:
        type: boolean
        required: false
        default: true
        description: 'Tells if unit tests should be run'
      publish-coverage:
        type: boolean
        required: false
        default: false
        description: 'Tells if code coverage should be published in codecov after running unit tests'
      force-install:
        type: boolean
        required: false
        default: false
        description: 'Tells if --force should be passed to npm ci command'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - run: ${{ inputs.force-install && 'npm ci --force' || 'npm ci' }}
      - run: npm run lint

  unit-tests:
    runs-on: ubuntu-22.04
    if: ${{ inputs.with-unit-tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - run: ${{ inputs.force-install && 'npm ci --force' || 'npm ci' }}
      - run: npm run test:ci
      - name: Publish coverage
        if: ${{ inputs.publish-coverage }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/clover.xml

  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: marceloprado/has-changed-path@v1
        id: changed-dockerfile
        with:
          paths: ./Dockerfile
      - if: ${{ steps.changed-dockerfile.outputs.changed == 'true' }}
        run: docker build -t shlink-website:test .
      - if: ${{ steps.changed-dockerfile.outputs.changed != 'true' }}
        run: echo "Dockerfile didn't change. Skipped"
