name: Continuous integration - Web app

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
        description: 'NodeJS version to use'
      with-unit-tests:
        type: boolean
        required: false
        default: true
        description: 'Tells if unit tests should be run'
      publish-coverage:
        type: boolean
        required: false
        default: false
        description: 'Tells if code coverage should be published in codecov after running unit tests'
      force-install:
        type: boolean
        required: false
        default: false
        description: 'Tells if --force should be passed to npm ci command'
      install-playwright:
        type: boolean
        required: false
        default: false
        description: 'Whether playwright dependencies should be installed before running tests. Defaults to false'

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        command: ['npm run lint', 'npm run types']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: ${{ inputs.force-install && 'npm ci --force' || 'npm ci' }}
      - run: ${{ matrix.command }}

  unit-tests:
    runs-on: ubuntu-24.04
    if: ${{ inputs.with-unit-tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: ${{ inputs.force-install && 'npm ci --force' || 'npm ci' }}
      - run: npx playwright install
        if: ${{ inputs.install-playwright }}
      - run: npm run test:ci
      - name: Publish coverage
        if: ${{ inputs.publish-coverage }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/clover.xml
